services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    ports:
    - "8000:8000"  # 외부에서 접근할 수 있는 포트 설정
    volumes:
      - ./config:/backend/config
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: "3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://be:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy  # backend 서비스가 건강할 때만 시작
