version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    volumes:
      - ./apps:/backend/apps
      - ./config:/backend/config
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy  # backend 서비스가 건강할 때만 시작
